[server]
bind_addr = "0.0.0.0:1000"
transport = "tcp"
accept_udp = false
token = "yamehdi"
keepalive_period = 10
nodelay = true
heartbeat = 40
channel_size = 2048
sniffer = false
web_port = 2525
sniffer_log = "/root/backhaul.json"
log_level = "info"
ports = [
 "8880=8880",
 "8443=8443",
 "4222=4222"]
